[package]
name = "pre-plantuml"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
  "Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "template package"
repository = "https://github.com/SillyFreak/typst-packages/tree/main/pre-plantuml"
categories = ["visualization"]
disciplines = []
keywords = ["uml", "diagram", "software", "modelling"]
compiler = "0.11.0"
exclude = [
  # docs and gallery are not needed in the final package
  "docs",
  "gallery",
]
